### PR TITLE
added arbitrary evaluation functions

### PR DESCRIPTION
**Pull request by charmoniumQ**

### CODE REVIEW

**Comment by NicolasHug** [comment]
Hi,

and thanks (again!). Is this feature something you really needed?
I would assume that as the evaluation function is quite trivial, people could just fun the cross-validation procedure manually and call the desired custom accuracy functions.

I'll leave the pull request opened, if this gets a lot of +1 I'll consider merging it.

Thanks! Nicolas

**Comment by charmoniumQ** [comment]
Do you mean people should copy-paste the cross-validation code? A small change would allow the existing code to work with any evaluation metric.

Of course, people (like me) who really need this functionality can set pip to install surprise from my git-repo.

Happy coding!

**Comment by NicolasHug** [comment]
> Do you mean people should copy-paste the cross-validation code?

Yes, the CV code is [really simple](http://surprise.readthedocs.io/en/stable/getting_started.html#manually-iterate-over-folds), and that's really just what `evaluate` is doing

**Comment by charmoniumQ** [comment]
Fair enough.

**Pull request closed without merging**
