### PR TITLE
update build_anti_testset

### PR DESCRIPTION
**Pull request by nju-luke**
1. Move the user_items out of the iteration.
2. Reconstruct the iteration as a constructor.

### CODE REVIEW

**Comment by NicolasHug** [comment]
Thanks for this.
There are issues related to the code style:
```
./surprise/dataset.py:698:73: E231 missing whitespace after ','
./surprise/dataset.py:699:14: E128 continuation line under-indented for visual indent
```

Anyway, the filter method is a bit overkill here. I'd rather use a simple list comprehension:
```
anti_testset += [(self.to_raw_uid(u), self.to_raw_iid(i), fill)
                 for i in self.all_items() if i not in user_items]
```

**Comment by NicolasHug** [comment]
I'm sorry if there's been a misunderstanding but to be clear: I'd gladly merge this PR provided that all the tests are passing.
My remark about the use of `filter()` is only a suggestion and my own view, I'm glad to hear your opinion on it. My point of view is that a simple list comprehension is easier to read and understand, but I may have missed something?

If I don't hear from you I'll implement the changes myself in a few days.
Nicolas

**Comment by nju-luke** [comment]
I'm so sorry that I have made some misunderstanding. And thank you for the suggestion. After some test, I find that the += operation and if condition is more efficient the extend and filter function.

**Comment by nju-luke** [comment]
Finally, I make the code style right. a ha ~~

**Comment by NicolasHug** [comment]
Thanks for the changes!
But why having modified all the `import` stuff, as well as [line 130](https://github.com/NicolasHug/Surprise/pull/106/files#diff-adb6f4535f8dbd436cbae854a5b4db0aL131)?

**Comment by nju-luke** [comment]
The order of $import$ stuff and the code style of line 130 were modified by pycharm automatically. Need me change back to the original version?

**Comment by NicolasHug** [comment]
Yes please, only keep the changes related to `build_anti_testset()`

**Comment by nju-luke** [comment]
Thank you very much for your patience。

**Comment by NicolasHug** [comment]
The import (and line 130) are still changed.
You may want to check the [contributing guidelines](https://github.com/NicolasHug/Surprise/blob/master/.github/CONTRIBUTING.md).

**Comment by nju-luke** [comment]
😂

**Comment by NicolasHug** [comment]
Perfect :)
Thanks!

**Pull request merged**
