### PR TITLE
allow no prompt on Dataset.from_builtin

### PR DESCRIPTION
**Pull request by ZachGlassman**
This allows download of a builtin without prompting.  Fixes https://github.com/NicolasHug/Surprise/issues/221

### CODE REVIEW

**Comment by NicolasHug** [comment]
Good idea, thanks!
Can you please update the docstring with the new parameter?

**Comment by ZachGlassman** [comment]
Done, thanks for your prompt feedback!

**Comment by ZachGlassman** [comment]
Added myself, looks like my editor also stripped whitespace, happy to put that back in if you would like to keep the diffs a bit cleaner.

**Comment by NicolasHug** [comment]
Awesome, thanks! :)

**Pull request merged**
