### PR TITLE
similarity on normalised data, knn with z-score normalisation

### PR DESCRIPTION
**Pull request by hengji-liu**
based on 

> A comprehensive survey of neighborhood-based recommendation methods

by Christian and George

### CODE REVIEW

**Comment by NicolasHug** [comment]
Hi,
Thanks for this!

The KNNWithZScore algorithm looks good to me!

However, I don't think that the `compute_similarities` method should be changed. You are here normalizing the ratings (either with z-score or just with the mean) before computing the pairwise similarities, and my opinion is that the way similarities are computed should be independent of the choice of the algorithm. That is, it's up to the user to choose (or not) a similarity measure that suits its prediction algorithm: this allows for more flexibility.

Any opinion on this?

Thanks,
Nicolas

**Comment by hengji-liu** [comment]
I see your point.

My thinking was that if user A's average rating is 2 and he gave movie M a 3 star rating, while user B's average rating is 4 and he gave M a 3 star rating as well. These two 3 star ratings don't mean the same thing. That's why I want to normalise it before computing . But I realised now that a cosine similarity on mean-normalised data would be the same as Pearson similarity. Besides that, those who use the package can normalise their data beforehand anyway. So I guess I'll remove the code on normalising?

Also, there are somethings I got but haven't pushed to GitHub
- fixing an error when initialising self.sigmas
- slight time complexity improvement in knn estimate (probably in another pull request, let this issue just be KNNWithZScore)
- paralleled RandomSearch class (probably in another pull request, or maybe my workmates will send a pull request from his repo)

**Comment by NicolasHug** [comment]
Hi,
Thanks for the changes! Sorry for the late notice I'm very busy right now.

> But I realised now that a cosine similarity on mean-normalised data would be the same as Pearson similarity.

Yes that's exactly why I think it's better to keep it as it is.

Could you please make the following changes (not much):

- Add `sigma_u` and `sigma_v` to the `notation_standards.rst` in the doc.
- change 'normalisation' to 'normalization' (I tend to use the US spelling, so it's just to keep it consistent)
- Indicate in the doc that if `sigma_u` or `sigma_v` is zero then it's replaced by the overall `sigma`.
- Revert change for `KNNWithMeans` as it's not needed anymore
- Add `KNNWithZScore` to `tests/test_algorithms.py:39` to check its behaviour when the given user or item is not known.
- If I'm not mistaken [overall_sigma](https://github.com/NicolasHug/Surprise/pull/83/files#diff-959e7de7ad0c049d5888d83a4ebaf250R359) could be computed with
`self.overall_sigma = np.std([r for (_, _, r) in self.trainset.all_ratings()])`?

Yes other PRs are more than welcome, but please keep them separate ;)

Thanks!
Nicolas

**Comment by hengji-liu** [comment]
I've done the changes according to your advice. Please check. Cheers.

**Comment by NicolasHug** [comment]
Perfect, thanks!

**Pull request merged**
