### PR TITLE
Fix Dataset builder pattern. Decouple Dataset and reader.

### PR DESCRIPTION
**Pull request by Sklavit**

### CODE REVIEW

**Comment by NicolasHug** [comment]
I agree that design for this part could be improved a lot. Could you please give details about the PR? Also all tests seem to be failing?

**Comment by Sklavit** [comment]
1. What do you mean by "the PR"?
2. Yes, I will fix tests.

**Comment by NicolasHug** [comment]
PR = Pull Request. The question is: what changes are you proposing?

**Comment by Sklavit** [comment]
Fastfix reader call in PredefinedKFold.split.
Actually, `reader` should not be called from `PredefinedKFold.split` because it leads to extra coupling. So I think a bit more redesign is needed. I will check it in a bt later.

**Comment by NicolasHug** [comment]
If the changes only affect `Dataset.split()` then it's probably not worth spending too much time on it: the `split()` method is deprecated and replaced by the use of CV iterators.

**Comment by Sklavit** [comment]
1. Move data preprocessing for building data sets into the dedicated functions (`load_from_df` and `load_from_file`) away from initializer (so `DatasetAutoFolds.__init__` will become trivial).
2. Move `read_ratings` to `Reader` because it is `Reader` functionality to read rating, not `DataSet`.

**Pull request closed without merging**
